# List all the driver
#all: qttest

qttest:	heap.cpp heap.h node.cpp node.h msttest.cpp 
	g++ -std=c++11 heap.cpp heap.h node.cpp node.h msttest.cpp -o msttest	

# List all the executables under 'all:'
clean:	
	rm *.o msttest 
