# List all the driversall: playlistdriver

playlistdriver:	playlistdriver.cpp song.cpp song.h playlist.h playlist.cpp 
	g++ -std=c++11 playlistdriver.cpp song.cpp playlist.cpp -o playlistdriver	

# List all the executables under 'all:'
clean:	
	rm *.o playlistdriver 
