all: undirectedGraphtest

undirectedGraphtest:	heap.cpp heap.h undirectedGraph.cpp undirectedGraph.h ugDriver.cpp ugDriver.h undirectedGraphtest.cpp 
	g++ -std=c++11 heap.cpp undirectedGraph.cpp ugDriver.cpp undirectedGraphtest.cpp  -o undirectedGraphtest	


clean:	
	rm *.o undirectedGraphtest 









