# List all the driversall: dequedriver

dequedriver:	linkList.cpp linkList.h node.cpp node.h dequedriver.cpp 
	g++ -std=c++11 dequedriver.cpp linkList.h node.cpp node.h linkList.cpp  -o dequedriver	

# List all the executables under 'all:'
clean:	
	rm *.o dequedriver 
