all: mstdriver

mstdriver:	mst.cpp mst.h node.cpp node.h illegal_argument.h illegal_argument.cpp msttest.cpp 
	g++ -std=c++11 mst.cpp mst.h node.cpp node.h msttest.cpp illegal_argument.h illegal_argument.cpp -o mstdriver	


clean:	
	rm *.o mstdriver 



