# List all the openhttest: openhttest
openhttest:	openhttest.cpp hasht.cpp hasht.h info.cpp info.h  
	g++ -std=c++11 hasht.cpp hasht.h info.cpp info.h openhttest.cpp  -o openhttest	

# List all the executables under 'all:'
clean:	
	rm *.o openhttest 







 
