# List all the driver
#all: qttest

qttest:	tree.cpp tree.h node.cpp node.h qttest.cpp 
	g++ -std=c++11 tree.cpp tree.h node.cpp node.h qttest.cpp -o qttest	

# List all the executables under 'all:'
clean:	
	rm *.o qttest 
